name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Get Repository Name
      run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      shell: bash
    -
      name: Set Image Tag Name - Master
      if: ${{ github.ref == 'refs/heads/master' }}
      run: echo "TAG_NAME=$(echo 'latest')" >> $GITHUB_ENV
      shell: bash
    -
      name: Set Image Tag Name - Other
      if: ${{ github.ref != 'refs/heads/master' }}
      run: echo "TAG_NAME=$(echo '${{ github.ref_name }}')" >> $GITHUB_ENV
      shell: bash
    -
      name: Checkout 
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.REPOSITORY_NAME }}:${{ env.TAG_NAME }}
