name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: |
        docker build \
          --build-arg http_proxy=$http_proxy \
          --build-arg https_proxy=$https_proxy \
          --build-arg no_proxy=$no_proxy \
          --build-arg VCS_REF=os.environ['GITHUB_SHA'] \
          --tag necrobraska/ansible-controller:latest \
         .
    - name: Push the Docker image
    - uses: actions/checkout@v2
    - run: docker push necrobraska/ansible-controller:latest
